version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: local_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - mongo_data:/data/db

volumes:
  mongo_data:
